---
engines:
  csslint:
    enabled: true
    checks:
      overqualified-elements:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    exclude_fingerprints:
      # Identical code found in 1 other location libs/a11yc/classes/validate/alt.php:116…119
      # reason: Necessity
      - 9fa587d72a53239e117c5c7c6b063d93
      # Similar code found in 1 other location libs/a11yc/classes/controller/docs.php:75…82
      # Similar code found in 1 other location libs/kontiki/classes/ua.php:51…57
      # reason: Maybe False detection
      - d3a8a3207356cb3666f66f66328a8dac
      - 30001ee64809e30f83511f043d45ae03
      # Identical code found in 1 other location libs/a11yc/classes/validate/validation.php:291…301
      # Identical code found in 1 other location libs/a11yc/classes/validate/validation.php:307…317
      # reason: Maybe False detection
      - f96b75d1e4620a3fbfa335ff99194b39
      - f96b75d1e4620a3fbfa335ff99194b39
      # Identical code found in 1 other location libs/a11yc/views/docs/each.php:66…76
      # reason: Maybe False detection
      - 73e992e43bb9e8fbac58ecf65fb9c9f2
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CyclomaticComplexity:
        enabled: false
      Design/ExitExpression:
        enabled: false
      Design/NpathComplexity:
        enabled: false
      Design/LongMethod:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- db/
- libs/spyc
- libs/guzzle
- libs/a11yc/css/font-awesome
